name: 'Staging preprod: Deploy Frontend'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'frontend/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/deploy-frontend-staging-preprod.yaml'

concurrency: frontend_staging

jobs:
  deploy:
    if: github.repository == 'WingRiders/multi-dex-launchpad'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod
      service: multi-dex-launchpad-frontend
      deploy: true
      working_directory: .
      dockerfile: frontend/Dockerfile
      build_args: |
        NEXT_PUBLIC_NETWORK=preprod
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
